### ISSUE TITLE
funky behavior with MPIBackend

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#215]
I have been trying to help @kohl-carmen set up `MPIBackend` on her Windows computer. The process just hangs for her [here](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/parallel_backends.py#L379) ... there seem to be some kind of deadlock going on somewhere. While trying to reproduce it on my Mac, I got a similar hanging behavior although I am not sure if it's exactly the same thing. To reproduce the hanging behavior on Mac, just "git cherry-pick" [this commit](https://github.com/jasmainak/hnn-core/commit/8d7f8f2b3bc47c34121bf5388f381305d4796cd4) and run the test you see in the diff:

```py
$ pytest ./hnn_core/tests/test_parallel_backends.py::test_run_mpibackend
```

@blakecaldwell any suggestions how to make this more robust?

**Comment by jasmainak** [comment]
also added the label "hnn-gui-integration" since I presume getting the `MPIBackend` to work is important for having Windows users benefit from the GUI?

**Comment by blakecaldwell** [comment]
It looks like you are causing an exception in the child, which will definitely make things hang:
https://github.com/jasmainak/hnn-core/commit/8d7f8f2b3bc47c34121bf5388f381305d4796cd4#diff-25efb3a0d8d1f3cde2a0b77ec4bb65c1407f187f566825c20274d445bca0a103R15

I realize the problem is likely rooted in something else, but I don't think this is reproducing it.

It looks like you are going down the right path for troubleshooting... try printing things instead of causing an exception. Looking toward the future, it'd probably be good to continue familiarizing yourselves with the MPI code. Feel free to tag me again if you feel like it's a rabbit hole.

**Comment by jasmainak** [comment]
humm ... but don't you agree that an exception should fail immediately? I have looked at the MPI code (see #211 ... waiting for review :) Basically, it means that any exception in the child process will be hidden with a "hang" ...

**Comment by blakecaldwell** [comment]
You're generalizing by saying, "any exception", which is incorrect. This is a specific point in the code. If the parent is not frozen, it can print messages to the console.
 
This issue has to do with multi-process programming, not really MPI specific. The parent is "frozen" trying to send parameters. If the child has an exception, then it will hang forever. You could implement a timeout, but that's a rabbit hole because it requires a separate thread to wait for the timeout.

**Comment by jasmainak** [comment]
> The parent is "frozen" trying to send parameters.

could you explain what's going on here a bit more? I understand the behavior but I fail to understand why this is happening. Is it because the stdin pipe needs to be closed from the child end for the parent to proceed?

**Comment by jasmainak** [comment]
If the child process has an exception, can't it send a signal to the `stdout` to exit with a `try`-`except`-`finally`or some kind of context manager? I don't want to add unnecessary complexity, but it would be good to understand what's going on and perhaps make some tweaks (if warranted) to make it easier for developers.

**Comment by jasmainak** [comment]
If the child process has an exception, can't it send a signal to the `stdout` to exit with a `try`-`except`-`finally`or some kind of context manager? I don't want to add unnecessary complexity, but it would be good to understand what's going on and perhaps make some tweaks (if warranted) to make it easier for developers.

**Comment by blakecaldwell** [comment]
I'm not sure my point is getting across that all I/O is blocking by default in Python. Code execution stops, where there is no ability to handle failures. These scenarios are tolerable if the code is simple and fast enough. If you translate try-except into system programming, you get multi-threaded programming and signals. It's just not worth it.

**Comment by blakecaldwell** [comment]
I can't reproduce this on a Mac with the latest code in #188.

Checking a windows system now.

**Comment by jasmainak** [comment]
Thanks a ton!

**Comment by blakecaldwell** [comment]
Okay. The MPIBackend may not work directly on windows. Only pytest "hung" for me. With `python examples/plot_simulated_evoked.py` there was a nice exception printed to the screen. It was not having to do with sending the parameters. Let me know if you saw something different.

BTW, @jasmainak something seems wrong with the mpi4py decorator. It skips all mpi tests even when it's installed.

@kohl-carmen I would suggesting Microsoft WSL instead (the HNN instructions may help) to move forward with this PR. That way the installation environment will be practically identical to a Linux system.

**Comment by blakecaldwell** [comment]
The exception:
```
(hnn-core) caldw@DESKTOP-LHCRPOM ~/repos/hnn-core$ python examples/plot_simulate_evoked.py
MPI will run over 2 processes
Running 1 trials...
MPIBackend sending parameters...
MPIBackend done sending parameters. Closing pipes
MPIBackend closed write side
MPIBackend closed read side
Traceback (most recent call last):
  File "examples/plot_simulate_evoked.py", line 100, in <module>
    dpls_sync = simulate_dipole(net_sync, n_trials=1)
  File "c:\users\caldw\repos\hnn-core\hnn_core\dipole.py", line 70, in simulate_dipole
    dpls = _BACKEND.simulate(net)
  File "c:\users\caldw\repos\hnn-core\hnn_core\parallel_backends.py", line 415, in simulate
    events = self.sel.select(timeout=1)
  File "C:\Users\caldw\Miniconda3\envs\hnn-core\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\caldw\Miniconda3\envs\hnn-core\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

**Comment by jasmainak** [comment]
> BTW, @jasmainak something seems wrong with the mpi4py decorator. It skips all mpi tests even when it's installed.

yeah ... I noticed that too. I'll open an issue

**Comment by jasmainak** [comment]
> The exception:

so what's your diagnosis? what's going on?

**Comment by jasmainak** [comment]
I think we managed to have @kohl-carmen 's PR move forward. However, it might be good to have this working for our future Windows users and developers? I was thinking of adding a CI for windows. See #167

**Comment by blakecaldwell** [comment]
Select on file descriptors doesn't work on Windows. 
https://docs.python.org/3/library/select.html#select.select

There's a way to do it instead with threads:
https://repolinux.wordpress.com/2012/10/09/non-blocking-read-from-stdin-in-python/

I won't be getting around to implement this for at least a couple of weeks. I would suggest Windows users use WSL. It'll make their life easier anyway using `pip install NEURON`.

**Comment by blakecaldwell** [comment]
> I was thinking of adding a CI for windows. See #167 
Sounds good. HNN has CI on WSL for windows.

**Comment by jasmainak** [comment]
Perfect, thanks for looking into it! I would say, no rush to implement it. Let's discuss this stuff more over zoom sometime. I want the code to be maintainable and make sure we are on the same page with this.

You might also want to take a look at [what is implemented in MNE for running subprocesses](https://github.com/mne-tools/mne-python/blob/529dd9ce448d2cbb2d987e4caa524c72cb2ab273/mne/utils/misc.py#L91). I'm not so fluent in multi-process programming, so perhaps if you could give us an overview of different alternatives and what features each lacks or adds, that would help? Having functions that are a bit more general and reusable are also helpful so that we can share and learn from each other in the community

**Comment by jasmainak** [comment]
github adventures led me here: https://stackoverflow.com/questions/375427/a-non-blocking-read-on-a-subprocess-pipe-in-python#4896288. Just leaving it here for later discussion

**Comment by blakecaldwell** [comment]
That's neat. I believe we will want to use very similar code.

**Comment by cjayb** [comment]
Hi @blakecaldwell , I did some hunting on this too and narrowed the problem down [to this line](https://github.com/jonescompneurolab/hnn-core/blob/a4a8ac025aaa2e768216192ab0a93409e75f1f96/hnn_core/parallel_backends.py#L445)

```python
                completion_signal = callback(key.fileobj, mask)
```

It [seems to be discussed in 2015, and then in 2020](https://bugs.python.org/issue25680) (by no other than BDFL himself!). Anyway, this might explain why the tests/examples run fine on my macOS (locally), but fail on CircleCI/Linux. The symptom is a single case of this line before the simulation is started, then the simulation, and finally 9 more similar lines after the simulation is completed

```bash
[54d15e9bf3de:07453] Read -1, expected 58804, errno = 1
```

Why this hangs on CircleCI (`python==3.6`), I don't know.

**Comment by jasmainak** [comment]
@cjayb if it's the same issue as this, I'm puzzled that CircleCI was working before with 3.6 ...

**Comment by cjayb** [comment]
Indeed, me too... I can only imagine that the underlying docker image has changed somehow?

**Comment by blakecaldwell** [comment]
Hey @jasmainak @cjayb, I think that the issues pointed out above on Windows and Linux using `select()` are good reasons to switch to a different scheme. The most confusing parts in `MPIBackend` are things that I added to make `select()` "work". So there'd be plenty to gain by switching to something cleaner and more portable... I like how MNE did it (thanks @jasmainak). Would either of you want to take on replacing the current subprocess code with [MNE's `run_subprocess`](https://github.com/mne-tools/mne-python/blob/main/mne/utils/misc.py#L91)?

**Comment by cjayb** [comment]
Thanks for the pointer to MNE! I was wondering whether the fact that we occasionally have CircleCI builds fail on macOS is explained by some sort of hardware caching. I.e., that CCI sends our builds to the same physical machine for several days in a row. Then, out of the blue, the build is sent to another machine, where it runs. I have no idea how likely this is! If true, it would point to some weakness in our macOS MPI-implementation at a very deep OS-level... Rather than try to dig further, going with the mne-implementation might be the way to go.

**Comment by blakecaldwell** [comment]
@cjayb Just want to point out that this problem really isn't about MPI. Using `Queue` instead of `select` or `selectors` is just an alternative to handling the MPI output. Can't say what was happening there with intermittent failures, that's weird, but it sounds more like software version inconsistencies as you mentioned earlier with docker images changing.
